import polygonClipping from 'polygon-clipping';
import { colorForLabel } from '@/lib/colors';
import { pointInRing, regionIntersectsRect } from '@/lib/geometry';
import type { Region } from '@/types/project';
import type { ProjectedSpot, TissueRegion, TissueSelectionSlice } from '@/types/built-in-admin';

type TissueParitySummary = NonNullable<TissueSelectionSlice['paritySummary']>;
type PolygonRing = [number, number][];
type PolygonGeometry = PolygonRing[];
type MultiPolygonGeometry = PolygonGeometry[];

export const AUTO_TISSUE_REGION_ID = 'tissue-auto-region';

export function isAutoGeneratedTissueRegion(region: Pick<TissueRegion, 'id'>): boolean {
  return region.id === AUTO_TISSUE_REGION_ID;
}

export function normalizeTissueRegion(region: TissueRegion): TissueRegion {
  return {
    ...region,
    paths: region.paths?.length ? region.paths : [region.points],
  };
}

const AUTO_REGION_EPSILON = 1e-9;

const ringSignedArea = (ring: TissueRegion['points']) => {
  let area = 0;
  for (let index = 0; index < ring.length; index += 1) {
    const current = ring[index];
    const next = ring[(index + 1) % ring.length];
    if (!current || !next) continue;
    area += current.x * next.y - next.x * current.y;
  }
  return area / 2;
};

export function getAutoGeneratedGeometryRegions(region: TissueRegion): Region[] {
  const normalized = normalizeTissueRegion(region);
  const paths = normalized.paths ?? [normalized.points];
  if (!paths.length) {
    return [];
  }

  const validPaths = paths.filter((path) => path.length >= 3);
  const indexedPaths = validPaths
    .map((path, index) => ({
      index,
      path,
      area: Math.abs(ringSignedArea(path)),
    }))
    .sort((left, right) => right.area - left.area);

  const outerRegions: Region[] = [];

  indexedPaths.forEach((candidate, candidateIndex) => {
    const anchor = candidate.path[0];
    if (!anchor) {
      return;
    }

    let containingDepth = 0;
    let bestRegionIndex = -1;
    let bestRegionArea = Number.POSITIVE_INFINITY;

    indexedPaths.forEach((potentialParent, potentialParentIndex) => {
      if (potentialParentIndex === candidateIndex || potentialParent.area <= candidate.area + AUTO_REGION_EPSILON) {
        return;
      }

      if (!pointInRing(anchor, potentialParent.path)) {
        return;
      }

      containingDepth += 1;
      if (potentialParent.area < bestRegionArea) {
        bestRegionArea = potentialParent.area;
        bestRegionIndex = potentialParentIndex;
      }
    });

    if (containingDepth % 2 === 0) {
      outerRegions.push({
        id: normalized.id,
        label: 0,
        color: normalized.color,
        points: candidate.path,
        paths: [candidate.path],
      });
      return;
    }

    const parentCandidate = indexedPaths[bestRegionIndex];
    if (!parentCandidate) {
      return;
    }

    const parentRegion = outerRegions.find((outerRegion) => outerRegion.points === parentCandidate.path);
    if (!parentRegion) {
      return;
    }

    parentRegion.paths = [...(parentRegion.paths ?? [parentRegion.points]), candidate.path];
  });

  if (outerRegions.length === 0) {
    return [toGeometryRegion(normalized)];
  }

  return outerRegions;
}

const toGeometryRegion = (region: TissueRegion): Region => {
  const normalized = normalizeTissueRegion(region);
  return {
    id: normalized.id,
    label: 0,
    color: normalized.color,
    points: normalized.points,
    paths: normalized.paths,
  };
};

export function deriveSelectedSpotIdsFromRegions(
  regions: TissueRegion[],
  projectedSpots: ProjectedSpot[],
): string[] {
  if (regions.length === 0) {
    return [];
  }

  const spotRects = projectedSpots.map((spot) => ({
    id: spot.id,
    rect: {
      x: spot.x - (spot.width ?? spot.diameterX) / 2,
      y: spot.y - (spot.height ?? spot.diameterY) / 2,
      width: spot.width ?? spot.diameterX,
      height: spot.height ?? spot.diameterY,
    },
  }));
  const geometryRegions = regions.flatMap((region) => {
    if (isAutoGeneratedTissueRegion(region)) {
      return getAutoGeneratedGeometryRegions(region);
    }

    return [toGeometryRegion(region)];
  });

  return spotRects
    .filter(({ rect }) => geometryRegions.some((region) => regionIntersectsRect(region, rect)))
    .map(({ id }) => id);
}

type SpotRect = {
  startX: number;
  endX: number;
  startY: number;
  endY: number;
  arrayRow: number;
  arrayCol: number;
};

const rectKey = (rect: Pick<SpotRect, 'startX' | 'endX'>) => [rect.startX, rect.endX]
  .map((value) => value.toFixed(9))
  .join(':');

const toSpotRect = (spot: ProjectedSpot): SpotRect => {
  const width = spot.width ?? spot.diameterX;
  const height = spot.height ?? spot.diameterY;
  return {
    startX: spot.x - width / 2,
    endX: spot.x + width / 2,
    startY: spot.y - height / 2,
    endY: spot.y + height / 2,
    arrayRow: spot.arrayRow,
    arrayCol: spot.arrayCol,
  };
};

const toPolygonGeometry = (rect: Pick<SpotRect, 'startX' | 'endX' | 'startY' | 'endY'>): PolygonGeometry => [[
  [rect.startX, rect.startY],
  [rect.endX, rect.startY],
  [rect.endX, rect.endY],
  [rect.startX, rect.endY],
]];

const buildMergedSpotPolygons = (spots: ProjectedSpot[]) => {
  const rows = new Map<number, SpotRect[]>();

  spots
    .map(toSpotRect)
    .sort((left, right) => left.arrayRow - right.arrayRow || left.arrayCol - right.arrayCol)
    .forEach((rect) => {
      const rowRects = rows.get(rect.arrayRow) ?? [];
      const previousRect = rowRects[rowRects.length - 1];
      if (previousRect && previousRect.arrayCol + 1 === rect.arrayCol) {
        previousRect.endX = rect.endX;
        previousRect.arrayCol = rect.arrayCol;
      } else {
        rowRects.push({ ...rect });
      }
      rows.set(rect.arrayRow, rowRects);
    });

  const merged: SpotRect[] = [];
  const activeByKey = new Map<string, SpotRect>();
  const sortedRows = Array.from(rows.entries()).sort((left, right) => left[0] - right[0]);

  sortedRows.forEach(([row, rowRects]) => {
    const nextActiveKeys = new Set<string>();

    rowRects.forEach((rect) => {
      const key = rectKey(rect);
      const activeRect = activeByKey.get(key);
      if (activeRect && activeRect.arrayRow + 1 === row) {
        activeRect.endY = rect.endY;
        activeRect.arrayRow = row;
      } else {
        activeByKey.set(key, { ...rect });
      }
      nextActiveKeys.add(key);
    });

    for (const [key, activeRect] of Array.from(activeByKey.entries())) {
      if (!nextActiveKeys.has(key)) {
        merged.push(activeRect);
        activeByKey.delete(key);
      }
    }
  });

  merged.push(...activeByKey.values());
  return merged.map(toPolygonGeometry);
};

export function buildDefaultTissueRegionFromDetectedSpots(args: {
  projectedSpots: ProjectedSpot[];
  selectedSpotIds: string[];
}): TissueRegion | null {
  const selectedIdSet = new Set(args.selectedSpotIds);
  const selectedSpots = args.projectedSpots.filter((spot) => selectedIdSet.has(spot.id));
  if (selectedSpots.length === 0) {
    return null;
  }

  const mergedSpotPolygons = buildMergedSpotPolygons(selectedSpots);
  let union: MultiPolygonGeometry = mergedSpotPolygons[0] ? [mergedSpotPolygons[0]] : [];
  for (const polygon of mergedSpotPolygons.slice(1)) {
    union = polygonClipping.union(union as never, polygon as never) as MultiPolygonGeometry;
  }
  const paths = union
    .flat()
    .filter((ring): ring is [number, number][] => Array.isArray(ring) && ring.length >= 3)
    .map((ring) => ring.slice(0, -1).map(([x, y]) => ({ x, y })));

  if (paths.length === 0) {
    return null;
  }

  return {
    id: AUTO_TISSUE_REGION_ID,
    label: 'Detected tissue',
    color: colorForLabel(0),
    points: paths[0],
    paths,
  };
}

export function buildSelectedCountSummary(selectedIds: string[], totalSpots: number): TissueParitySummary {
  const selectedCount = selectedIds.length;
  const selectedPercent = totalSpots > 0 ? (selectedCount / totalSpots) * 100 : 0;

  return {
    selectedCount,
    selectedPercent,
    maskCoverage: selectedPercent,
  };
}
