import { ChakraProvider } from '@chakra-ui/react';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';

import { theme } from '../../../theme';
import type { PreprocessProjectSummary } from '@/lib/preprocess/storage';
import { PreprocessLanding } from './PreprocessLanding';

const createProjectSummary = (): PreprocessProjectSummary => ({
  id: 'preprocess-copy-project',
  name: 'Copy QA project',
  createdAt: '2026-04-15T00:00:00.000Z',
  updatedAt: '2026-04-16T00:00:00.000Z',
  currentStep: 'heFocus',
  sourceAssets: {
    status: 'complete',
    isStale: false,
    updatedAt: '2026-04-16T00:00:00.000Z',
    error: null,
    activeImage: 'eosin',
    images: {
      eosin: {
        id: 'eosin-source',
        kind: 'eosin',
        fileName: 'eosin.png',
        mimeType: 'image/png',
        sizeBytes: 10,
        width: 100,
        height: 100,
        lastModified: 1,
      },
      he: {
        id: 'he-source',
        kind: 'he',
        fileName: 'he.png',
        mimeType: 'image/png',
        sizeBytes: 10,
        width: 100,
        height: 100,
        lastModified: 1,
      },
    },
    oversizedImageWarning: null,
  },
});

type RenderLandingOptions = {
  readonly onCreateProject?: () => void;
  readonly onDeleteProject?: (projectId: string) => void;
  readonly onImportProject?: (fileList: FileList | null) => void;
  readonly onOpenProject?: (projectId: string) => void;
  readonly projectName?: string;
  readonly projects?: readonly PreprocessProjectSummary[];
};

const renderLanding = ({
  onCreateProject = vi.fn(),
  onDeleteProject = vi.fn(),
  onImportProject = vi.fn(),
  onOpenProject = vi.fn(),
  projectName = '',
  projects = [],
}: RenderLandingOptions = {}) => render(
  <ChakraProvider theme={theme}>
    <PreprocessLanding
      isCreating={false}
      isDeletingId={null}
      isImporting={false}
      onCreateProject={onCreateProject}
      onDeleteProject={onDeleteProject}
      onImportProject={onImportProject}
      onOpenProject={onOpenProject}
      projectName={projectName}
      projects={projects}
      setProjectName={vi.fn()}
    />
  </ChakraProvider>,
);

describe('PreprocessLanding copy policy', () => {
  it('matches the project-selection copy contract', () => {
    renderLanding();

    expect(screen.getAllByText('LOCAL PROCESSING')).toHaveLength(1);
    expect(screen.getByText('Create, manage, and continue preprocessing projects for image registration, tissue spot selection, and downstream analysis in NATA Insight Bioinformatics Software. All project data is processed and stored locally in your browser.')).toBeInTheDocument();
    expect(screen.getByText('Create a new preprocessing project for a tissue section.')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Import Preprocessing Package' })).toBeInTheDocument();
    expect(screen.getByText('Import a previously exported preprocessing package to continue editing or resume preprocessing.')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Select Package' })).toBeInTheDocument();
    expect(screen.getByText('Only valid preprocessing packages generated by NATAScope can be imported.')).toBeInTheDocument();
    expect(screen.getByText('Open an existing preprocessing project or continue working on an imported project.')).toBeInTheDocument();

    const shell = screen.getByTestId('preprocess-landing-shell');
    expect(within(shell).queryByText('Stored locally')).not.toBeInTheDocument();
  });

  it('uses HE terminology in saved project source and step summaries', () => {
    renderLanding({ projects: [createProjectSummary()] });

    const projectList = screen.getByTestId('preprocess-project-list');
    expect(within(projectList).getByText('Current step: HE focus')).toBeInTheDocument();
    expect(within(projectList).getByText('Eosin reference + HE')).toBeInTheDocument();
    expect(projectList).not.toHaveTextContent('H&E');
  });

  it('keeps create, import, open, and delete actions wired', () => {
    const onCreateProject = vi.fn<() => void>();
    const onDeleteProject = vi.fn<(projectId: string) => void>();
    const onImportProject = vi.fn<(fileList: FileList | null) => void>();
    const onOpenProject = vi.fn<(projectId: string) => void>();

    const { container } = renderLanding({
      onCreateProject,
      onDeleteProject,
      onImportProject,
      onOpenProject,
      projectName: 'Copy QA project',
      projects: [createProjectSummary()],
    });

    fireEvent.click(screen.getByTestId('preprocess-create-project'));
    expect(onCreateProject).toHaveBeenCalledTimes(1);

    fireEvent.click(screen.getByRole('button', { name: 'Open workspace' }));
    expect(onOpenProject).toHaveBeenCalledWith('preprocess-copy-project');

    fireEvent.click(screen.getByRole('button', { name: 'Delete Copy QA project' }));
    expect(onDeleteProject).toHaveBeenCalledWith('preprocess-copy-project');

    const fileInput = container.querySelector<HTMLInputElement>('input[type="file"]');
    expect(fileInput).not.toBeNull();
    if (fileInput === null) {
      throw new Error('Import input missing');
    }

    const file = new File(['{}'], 'copy.spatial-preprocess.json', { type: 'application/json' });
    fireEvent.change(fileInput, { target: { files: [file] } });

    expect(onImportProject).toHaveBeenCalledTimes(1);
    expect(onImportProject.mock.calls[0]?.[0]?.[0]).toBe(file);
  });
});
