'use client';

import {
  Box,
  Button,
  ButtonGroup,
  Card,
  CardBody,
  Flex,
  HStack,
  Stack,
  Text,
  useToast,
} from '@chakra-ui/react';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import polygonClipping from 'polygon-clipping';
import {
  computeBaseView,
  computeZoomTransform,
  getTransform,
  relativeToImage,
} from '@/lib/canvasViewport';
import { colorForLabel } from '@/lib/colors';
import { pointInRegion } from '@/lib/geometry';
import { getAutoGeneratedGeometryRegions, isAutoGeneratedTissueRegion } from '@/lib/preprocess/tissueRegions';
import type { Point, Region } from '@/types/project';
import type { PreprocessPoint, ProjectedSpot, TissueRegion } from '@/types/preprocess';

type ToolMode = 'draw' | 'edit' | 'erase';

export type { ToolMode };

type TissueSelectionPanelProps = {
  eosinCropDataUrl: string | null;
  projectedSpots: ProjectedSpot[];
  selectedSpotIds: string[];
  regions: TissueRegion[];
  selectedRegionId: string | null;
  disabled?: boolean;
  showControls?: boolean;
  tool?: ToolMode;
  onToolChange?: (tool: ToolMode) => void;
  onDeleteSelected?: () => void;
  onRegionsChange: (regions: TissueRegion[]) => void;
  onSelectedRegionIdChange: (id: string | null) => void;
};

export function TissueSelectionPanel({
  eosinCropDataUrl,
  projectedSpots,
  selectedSpotIds,
  regions,
  selectedRegionId,
  disabled = false,
  showControls = true,
  tool: controlledTool,
  onToolChange,
  onDeleteSelected,
  onRegionsChange,
  onSelectedRegionIdChange,
}: TissueSelectionPanelProps) {
  const toast = useToast();
  const [internalTool, setInternalTool] = useState<ToolMode>('edit');
  const [selectedRegionIds, setSelectedRegionIds] = useState<string[]>([]);
  const [selectionAnchor, setSelectionAnchor] = useState<number | null>(null);
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [isDrawing, setIsDrawing] = useState(false);
  const [, setIsPanning] = useState(false);
  const [canvasRefresh, setCanvasRefresh] = useState(0);
  const [imageDimensions, setImageDimensions] = useState<{ width: number; height: number } | null>(null);

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const hostRef = useRef<HTMLDivElement | null>(null);
  const loadedImageRef = useRef<HTMLImageElement | null>(null);
  const pathRef = useRef<PreprocessPoint[]>([]);
  const canvasRefreshFrameRef = useRef<number | null>(null);
  const panStartRef = useRef<{ x: number; y: number } | null>(null);
  const drawingActiveRef = useRef(false);
  const panningActiveRef = useRef(false);
  const [hostRect, setHostRect] = useState<DOMRect | null>(null);

  const requestCanvasRefresh = useCallback(() => {
    if (canvasRefreshFrameRef.current !== null) {
      return;
    }

    canvasRefreshFrameRef.current = window.requestAnimationFrame(() => {
      canvasRefreshFrameRef.current = null;
      setCanvasRefresh((value) => value + 1);
    });
  }, []);

  useEffect(() => {
    if (!eosinCropDataUrl) {
      loadedImageRef.current = null;
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setImageDimensions(null);
      return;
    }
    const image = new Image();
    image.src = eosinCropDataUrl;
    image.onload = () => {
      loadedImageRef.current = image;
      setImageDimensions({ width: image.width, height: image.height });
      requestCanvasRefresh();
    };
  }, [eosinCropDataUrl, requestCanvasRefresh]);

  useEffect(() => () => {
    if (canvasRefreshFrameRef.current !== null) {
      window.cancelAnimationFrame(canvasRefreshFrameRef.current);
    }
  }, []);

  useEffect(() => {
    if (!hostRef.current) return;
    const updateRect = () => {
      if (!hostRef.current) return;
      setHostRect(hostRef.current.getBoundingClientRect());
    };

    updateRect();
    const observer = new ResizeObserver(() => {
      updateRect();
    });
    observer.observe(hostRef.current);
    window.addEventListener('resize', updateRect);
    return () => {
      observer.disconnect();
      window.removeEventListener('resize', updateRect);
    };
  }, []);

  const ratio = useMemo(() => {
    if (!imageDimensions) return 4 / 3;
    return imageDimensions.width / imageDimensions.height;
  }, [imageDimensions]);

  const effectiveSelectedRegionIds = useMemo(() => {
    if (!selectedRegionId) return [];
    return selectedRegionIds.length > 1 && selectedRegionIds.includes(selectedRegionId)
      ? selectedRegionIds
      : [selectedRegionId];
  }, [selectedRegionId, selectedRegionIds]);
  const selectedSpotIdSet = useMemo(() => new Set(selectedSpotIds), [selectedSpotIds]);
  const selectedRegionIdSet = useMemo(() => new Set(effectiveSelectedRegionIds), [effectiveSelectedRegionIds]);

  const computeBaseViewCb = useCallback(
    () => computeBaseView(hostRect, ratio),
    [hostRect, ratio],
  );

  const getLiveHostRect = useCallback(() => hostRef.current?.getBoundingClientRect() ?? hostRect, [hostRect]);

  const getTransformCb = useCallback(
    () => getTransform(computeBaseViewCb(), zoom, pan),
    [computeBaseViewCb, pan, zoom],
  );

  const relativeToImageCb = useCallback(
    (relative: Point | null) => relativeToImage(relative, getTransformCb()),
    [getTransformCb],
  );

  const screenToImage = useCallback(
    (event: React.PointerEvent<HTMLCanvasElement>): Point | null => {
      const currentHostRect = getLiveHostRect();
      if (!currentHostRect) return null;
      const relative = {
        x: event.clientX - currentHostRect.left,
        y: event.clientY - currentHostRect.top,
      };
      return relativeToImageCb(relative);
    },
    [getLiveHostRect, relativeToImageCb],
  );

  const getRegionPaths = useCallback((region: TissueRegion): PreprocessPoint[][] => {
    return region.paths?.length ? region.paths : [region.points];
  }, []);

  const pointInTissueRegion = useCallback(
    (point: Point, region: TissueRegion): boolean => {
      if (isAutoGeneratedTissueRegion(region)) {
        return getAutoGeneratedGeometryRegions(region).some((geometryRegion) =>
          pointInRegion(point, geometryRegion),
        );
      }

      const geometryRegion: Region = {
        id: region.id,
        label: 0,
        color: region.color,
        points: region.points,
        paths: getRegionPaths(region),
      };
      return pointInRegion(point, geometryRegion);
    },
    [getRegionPaths],
  );

  const findRegionAtPoint = useCallback(
    (point: Point): TissueRegion | null => {
      for (let i = 0; i < regions.length; i += 1) {
        const region = regions[i];
        if (pointInTissueRegion(point, region)) return region;
      }
      return null;
    },
    [regions, pointInTissueRegion],
  );

  const selectRegionByIndex = useCallback(
    (index: number, modifiers: { ctrlKey: boolean; metaKey: boolean; shiftKey: boolean }) => {
      if (index < 0 || index >= regions.length) return;
      const id = regions[index].id;
      const ctrl = modifiers.ctrlKey || modifiers.metaKey;
      const shift = modifiers.shiftKey;

      if (shift && selectionAnchor !== null) {
        const start = Math.min(selectionAnchor, index);
        const end = Math.max(selectionAnchor, index);
        const rangeIds = regions.slice(start, end + 1).map((r) => r.id);
        if (ctrl) {
          setSelectedRegionIds((prev) => Array.from(new Set([...prev, ...rangeIds])));
        } else {
          setSelectedRegionIds(rangeIds);
        }
        setSelectionAnchor(index);
        onSelectedRegionIdChange(id);
        return;
      }

      if (ctrl) {
        setSelectionAnchor(index);
        const nextSelectedRegionIds = effectiveSelectedRegionIds.includes(id)
          ? effectiveSelectedRegionIds.filter((currentId) => currentId !== id)
          : [...effectiveSelectedRegionIds, id];
        setSelectedRegionIds(nextSelectedRegionIds);
        onSelectedRegionIdChange(nextSelectedRegionIds.at(-1) ?? null);
        return;
      }

      setSelectionAnchor(index);
      setSelectedRegionIds([id]);
      onSelectedRegionIdChange(id);
    },
    [effectiveSelectedRegionIds, regions, selectionAnchor, onSelectedRegionIdChange],
  );

  const activeTool = controlledTool ?? internalTool;
  const handleToolChange = useCallback(
    (nextTool: ToolMode) => {
      if (controlledTool === undefined) {
        setInternalTool(nextTool);
      }
      onToolChange?.(nextTool);
    },
    [controlledTool, onToolChange],
  );

  const deleteSelectedRegions = useCallback(() => {
    if (disabled) return;
    if (onDeleteSelected) {
      onDeleteSelected();
      return;
    }
    if (effectiveSelectedRegionIds.length === 0) return;
    const remove = new Set(effectiveSelectedRegionIds);
    const next = regions.filter((region) => !remove.has(region.id));
    onRegionsChange(next);
    setSelectedRegionIds([]);
    setSelectionAnchor(null);
    onSelectedRegionIdChange(null);
  }, [disabled, effectiveSelectedRegionIds, onDeleteSelected, regions, onRegionsChange, onSelectedRegionIdChange]);

  const commitRegion = useCallback(
    (points: PreprocessPoint[]) => {
      if (disabled || points.length < 3) return;
      const region: TissueRegion = {
        id:
          typeof crypto !== 'undefined' && crypto.randomUUID
            ? crypto.randomUUID()
            : `region-${Date.now()}`,
        label: `Region ${regions.length + 1}`,
        color: colorForLabel(regions.length),
        points,
        paths: [points],
      };
      onRegionsChange([...regions, region]);
      setSelectedRegionIds([region.id]);
      setSelectionAnchor(regions.length);
      onSelectedRegionIdChange(region.id);
    },
    [disabled, regions, onRegionsChange, onSelectedRegionIdChange],
  );

  const punchOut = useCallback(
    (erasePath: PreprocessPoint[]) => {
      if (disabled || erasePath.length < 3 || effectiveSelectedRegionIds.length === 0) return;
      const eraserPolygon = [erasePath.map((p) => [p.x, p.y] as [number, number])];

      const nextRegions: TissueRegion[] = [];
      const nextSelected: string[] = [];

      regions.forEach((region) => {
        if (!effectiveSelectedRegionIds.includes(region.id)) {
          nextRegions.push(region);
          return;
        }

        const sourceMulti: [number, number][][][] = isAutoGeneratedTissueRegion(region)
          ? getAutoGeneratedGeometryRegions(region).map((geometryRegion) =>
              getRegionPaths({
                ...region,
                points: geometryRegion.points,
                paths: geometryRegion.paths?.map((path) => path.map((point) => ({ ...point }))),
              }).map((ring) => ring.map((p) => [p.x, p.y] as [number, number])),
            )
          : [
              getRegionPaths(region).map((ring) =>
                ring.map((p) => [p.x, p.y] as [number, number]),
              ),
            ];

        const diff = polygonClipping.difference(sourceMulti, [eraserPolygon]);

        if (!diff || diff.length === 0) {
          return;
        }

        diff.forEach((poly, idx) => {
          if (!poly || poly.length === 0) return;
          const outer = poly[0];
          if (!outer || outer.length < 3) return;
          const holes = poly.slice(1);

          const toPoints = (ring: [number, number][]) =>
            ring.map(([x, y]) => ({ x, y }));
          const paths = [toPoints(outer), ...holes.map(toPoints)];
          const id = idx === 0 ? region.id : `${region.id}-${idx}`;
          nextRegions.push({ ...region, id, points: paths[0], paths });
          nextSelected.push(id);
        });
      });

      onRegionsChange(nextRegions);
      setSelectedRegionIds(nextSelected);
      setSelectionAnchor(null);
      onSelectedRegionIdChange(nextSelected[0] ?? null);
    },
    [disabled, effectiveSelectedRegionIds, getRegionPaths, onRegionsChange, regions, onSelectedRegionIdChange],
  );

  const resetInteractionState = useCallback(() => {
    drawingActiveRef.current = false;
    panningActiveRef.current = false;
    pathRef.current = [];
    setIsDrawing(false);
    setIsPanning(false);
    panStartRef.current = null;
    requestCanvasRefresh();
  }, [requestCanvasRefresh]);

  const handlePointerDown = useCallback(
    (event: React.PointerEvent<HTMLCanvasElement>) => {
      if (disabled) {
        resetInteractionState();
        event.preventDefault();
        return;
      }
      const isMiddleButton = event.button === 1;
      const point = screenToImage(event);
      event.currentTarget.setPointerCapture(event.pointerId);

      if (isMiddleButton) {
        event.preventDefault();
        panStartRef.current = { x: event.clientX, y: event.clientY };
        panningActiveRef.current = true;
        setIsPanning(true);
        return;
      }

      if (!point) return;

      if (activeTool === 'edit') {
        const hit = findRegionAtPoint(point);
        if (hit) {
          const hitIndex = regions.findIndex((r) => r.id === hit.id);
          selectRegionByIndex(hitIndex, {
            ctrlKey: event.ctrlKey,
            metaKey: event.metaKey,
            shiftKey: event.shiftKey,
          });
          return;
        }
        panStartRef.current = { x: event.clientX, y: event.clientY };
        panningActiveRef.current = true;
        setIsPanning(true);
        return;
      }

      if (activeTool === 'erase') {
        if (effectiveSelectedRegionIds.length === 0) {
          toast({
            title: 'Select a region first',
            status: 'info',
            duration: 1400,
          });
          return;
        }
        pathRef.current = [point];
        drawingActiveRef.current = true;
        setIsDrawing(true);
        requestCanvasRefresh();
        return;
      }

      pathRef.current = [point];
      drawingActiveRef.current = true;
      setIsDrawing(true);
      requestCanvasRefresh();
    },
    [activeTool, disabled, effectiveSelectedRegionIds, findRegionAtPoint, regions, requestCanvasRefresh, resetInteractionState, screenToImage, selectRegionByIndex, toast],
  );

  const handlePointerMove = useCallback(
    (event: React.PointerEvent<HTMLCanvasElement>) => {
      if (disabled) {
        resetInteractionState();
        return;
      }
      if (panningActiveRef.current) {
        if (!panStartRef.current) return;
        const dx = event.clientX - panStartRef.current.x;
        const dy = event.clientY - panStartRef.current.y;
        setPan((prev) => ({ x: prev.x + dx, y: prev.y + dy }));
        panStartRef.current = { x: event.clientX, y: event.clientY };
        return;
      }
      const point = screenToImage(event);
      if (!drawingActiveRef.current || (activeTool !== 'draw' && activeTool !== 'erase') || !point) return;
      pathRef.current.push(point);
      requestCanvasRefresh();
    },
    [activeTool, disabled, requestCanvasRefresh, resetInteractionState, screenToImage],
  );

  const handlePointerUp = useCallback((event: React.PointerEvent<HTMLCanvasElement>) => {
    if (disabled) {
      resetInteractionState();
      if (event.currentTarget.hasPointerCapture(event.pointerId)) {
        event.currentTarget.releasePointerCapture(event.pointerId);
      }
      return;
    }
    if (panningActiveRef.current) {
      panningActiveRef.current = false;
      setIsPanning(false);
      panStartRef.current = null;
      return;
    }
    if (!drawingActiveRef.current || (activeTool !== 'draw' && activeTool !== 'erase')) return;
    drawingActiveRef.current = false;
    setIsDrawing(false);
    if (activeTool === 'erase') {
      punchOut(pathRef.current);
    } else {
      commitRegion(pathRef.current);
    }
    pathRef.current = [];
    requestCanvasRefresh();
    event.currentTarget.releasePointerCapture(event.pointerId);
  }, [activeTool, commitRegion, disabled, punchOut, requestCanvasRefresh, resetInteractionState]);

  const applyZoom = useCallback(
    (rawZoom: number, anchorNorm?: Point, anchorScreen?: Point) => {
      const result = computeZoomTransform(computeBaseViewCb(), rawZoom, anchorNorm, anchorScreen);
      if (!result) return;
      setZoom(result.zoom);
      setPan(result.pan);
    },
    [computeBaseViewCb],
  );

  const handleWheel = useCallback(
    (event: React.WheelEvent<HTMLCanvasElement>) => {
      if (disabled) {
        resetInteractionState();
        event.preventDefault();
        return;
      }
      const currentHostRect = getLiveHostRect();
      if (!currentHostRect) return;
      const anchorScreen = {
        x: event.clientX - currentHostRect.left,
        y: event.clientY - currentHostRect.top,
      };
      const anchorNorm = relativeToImageCb(anchorScreen);
      if (!anchorNorm) return;
      const delta = event.deltaY > 0 ? 0.9 : 1.1;
      applyZoom(zoom * delta, anchorNorm, anchorScreen);
    },
    [disabled, getLiveHostRect, relativeToImageCb, applyZoom, resetInteractionState, zoom],
  );

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !hostRect) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    void canvasRefresh;

    canvas.width = hostRect.width;
    canvas.height = hostRect.height;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    const transform = getTransformCb();
    if (!transform) return;

    const image = loadedImageRef.current;
    if (image) {
      ctx.drawImage(
        image,
        transform.originX,
        transform.originY,
        transform.width,
        transform.height,
      );
    }

    projectedSpots.forEach((spot) => {
      const normalizedSpotWidth = spot.width ?? spot.diameterX ?? 0;
      const normalizedSpotHeight = spot.height ?? spot.diameterY ?? normalizedSpotWidth;
      const spotWidth = Math.max(1, normalizedSpotWidth * transform.width);
      const spotHeight = Math.max(1, normalizedSpotHeight * transform.height);
      const spotX = transform.originX + spot.x * transform.width - spotWidth / 2;
      const spotY = transform.originY + spot.y * transform.height - spotHeight / 2;
      const selected = selectedSpotIdSet.has(spot.id);
      ctx.fillStyle = selected ? 'rgba(46,204,113,0.35)' : 'rgba(231,76,60,0.2)';
      ctx.fillRect(spotX, spotY, spotWidth, spotHeight);
      ctx.strokeStyle = selected ? 'rgba(39,174,96,0.8)' : 'rgba(192,57,43,0.7)';
      ctx.strokeRect(spotX, spotY, spotWidth, spotHeight);
    });

    regions.forEach((region) => {
      const paths = getRegionPaths(region);
      const isSelected = selectedRegionIdSet.has(region.id);
      if (paths.length === 0) return;
      ctx.beginPath();
      paths.forEach((ring) => {
        if (ring.length < 2) return;
        const first = ring[0];
        ctx.moveTo(
          transform.originX + first.x * transform.width,
          transform.originY + first.y * transform.height,
        );
        for (let i = 1; i < ring.length; i += 1) {
          const p = ring[i];
          ctx.lineTo(
            transform.originX + p.x * transform.width,
            transform.originY + p.y * transform.height,
          );
        }
        ctx.closePath();
      });
      ctx.fillStyle = isSelected ? 'rgba(66,153,225,0.25)' : 'rgba(66,153,225,0.15)';
      ctx.fill('evenodd');
      ctx.strokeStyle = isSelected ? 'rgba(66,153,225,0.9)' : 'rgba(66,153,225,0.6)';
      ctx.lineWidth = isSelected ? 2 : 1;
      ctx.stroke();
    });

    const currentPoints = pathRef.current;
    if (isDrawing && currentPoints.length > 0) {
      ctx.beginPath();
      const first = currentPoints[0];
      ctx.moveTo(
        transform.originX + first.x * transform.width,
        transform.originY + first.y * transform.height,
      );
      for (let i = 1; i < currentPoints.length; i += 1) {
        const p = currentPoints[i];
        ctx.lineTo(
          transform.originX + p.x * transform.width,
          transform.originY + p.y * transform.height,
        );
      }
      ctx.strokeStyle = activeTool === 'erase' ? 'rgba(255,0,0,0.8)' : 'rgba(0,255,0,0.8)';
      ctx.lineWidth = 2;
      ctx.stroke();
    }
  }, [
    hostRect,
    canvasRefresh,
    projectedSpots,
    selectedSpotIdSet,
    regions,
    selectedRegionIdSet,
    isDrawing,
    activeTool,
    getTransformCb,
    getRegionPaths,
  ]);

  return (
    <Card border='1px solid' borderColor='gray.200' borderRadius='2xl' boxShadow='sm' bg='white'>
      <CardBody p={{ base: 4, xl: 5 }}>
        <Stack spacing={4} h='100%'>
          <Flex
            justify='space-between'
            align={{ base: 'flex-start', md: 'center' }}
            gap={3}
            direction={{ base: 'column', md: 'row' }}
          >
            <Stack spacing={1}>
              <Text fontSize='lg' fontWeight='semibold'>Tissue workspace</Text>
              <Text fontSize='sm' color='gray.500'>
                Review the dominant tissue canvas, then refine the auto-generated region with edit, draw, and punch out.
              </Text>
            </Stack>
            <HStack spacing={3} wrap='wrap' justify={{ base: 'flex-start', md: 'flex-end' }}>
              <Text data-testid='tissue-panel-selected-count' fontSize='sm' color='gray.600'>
                Selected spots: {selectedSpotIds.length}
              </Text>
              {showControls ? (
                <Button
                  size='xs'
                  colorScheme='red'
                  variant='outline'
                  isDisabled={disabled || effectiveSelectedRegionIds.length === 0}
                  onClick={deleteSelectedRegions}
                  data-testid='tissue-delete-selected'
                >
                  Delete selected
                </Button>
              ) : null}
            </HStack>
          </Flex>

          <Box
            ref={hostRef}
            position='relative'
            border='1px solid'
            borderColor='gray.200'
            borderRadius='xl'
            overflow='hidden'
            bg='gray.50'
            pointerEvents={disabled ? 'none' : 'auto'}
            minH={{ base: '420px', xl: '680px' }}
            opacity={disabled ? 0.8 : 1}
            data-testid='tissue-stage-canvas'
          >
            <canvas
              ref={canvasRef}
              style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', display: 'block', touchAction: 'none', pointerEvents: 'auto' }}
              onPointerDown={handlePointerDown}
              onPointerMove={handlePointerMove}
              onPointerUp={handlePointerUp}
              onPointerLeave={handlePointerUp}
              onPointerCancel={handlePointerUp}
              onWheel={handleWheel}
            />
          </Box>

          {showControls ? (
            <Stack spacing={3}>
              <ButtonGroup size='sm' isAttached variant='outline' alignSelf='flex-start'>
                <Button
                  data-testid='tissue-tool-edit'
                  colorScheme={activeTool === 'edit' ? 'brand' : 'gray'}
                  isDisabled={disabled}
                  onClick={() => handleToolChange('edit')}
                >
                  Edit
                </Button>
                <Button
                  data-testid='tissue-tool-draw'
                  colorScheme={activeTool === 'draw' ? 'brand' : 'gray'}
                  isDisabled={disabled}
                  onClick={() => handleToolChange('draw')}
                >
                  Draw
                </Button>
                <Button
                  data-testid='tissue-tool-erase'
                  colorScheme={activeTool === 'erase' ? 'brand' : 'gray'}
                  isDisabled={disabled}
                  onClick={() => handleToolChange('erase')}
                >
                  Punch Out
                </Button>
              </ButtonGroup>

              <Stack spacing={2} maxH='240px' overflowY='auto'>
                {regions.map((region, index) => (
                  <HStack
                    key={region.id}
                    p={3}
                    bg={selectedRegionIdSet.has(region.id) ? 'brand.50' : 'white'}
                    border='1px solid'
                    borderColor={selectedRegionIdSet.has(region.id) ? 'brand.200' : 'gray.200'}
                    borderRadius='lg'
                    cursor={disabled ? 'not-allowed' : 'pointer'}
                    opacity={disabled ? 0.6 : 1}
                    data-testid='tissue-region-row'
                    onClick={(e) => {
                      if (disabled) {
                        return;
                      }
                      selectRegionByIndex(index, {
                        ctrlKey: e.ctrlKey,
                        metaKey: e.metaKey,
                        shiftKey: e.shiftKey,
                      });
                    }}
                  >
                    <Box w='12px' h='12px' borderRadius='sm' bg={region.color} />
                    <Text fontSize='sm' flex='1' fontWeight='medium'>
                      {region.label}
                    </Text>
                  </HStack>
                ))}
                {regions.length === 0 ? (
                  <Box border='1px dashed' borderColor='gray.200' borderRadius='lg' px={3} py={4}>
                    <Text fontSize='sm' color='gray.500'>
                      No tissue regions yet. Run auto detection to generate the default editable region.
                    </Text>
                  </Box>
                ) : null}
              </Stack>
            </Stack>
          ) : null}
        </Stack>
      </CardBody>
    </Card>
  );
}
