import polygonClipping from 'polygon-clipping';
import { colorForLabel } from '@/lib/colors';
import { pointInRing, regionIntersectsRect } from '@/lib/geometry';
import type { Region } from '@/types/project';
import type { ProjectedSpot, TissueRegion, TissueSelectionSlice } from '@/types/preprocess';

type TissueParitySummary = NonNullable<TissueSelectionSlice['paritySummary']>;
type PolygonRing = [number, number][];
type PolygonGeometry = PolygonRing[];
type MultiPolygonGeometry = PolygonGeometry[];

export const AUTO_TISSUE_REGION_ID = 'tissue-auto-region';

export function isAutoGeneratedTissueRegion(region: Pick<TissueRegion, 'id'>): boolean {
  return region.id === AUTO_TISSUE_REGION_ID;
}

export function normalizeTissueRegion(region: TissueRegion): TissueRegion {
  return {
    ...region,
    paths: region.paths?.length ? region.paths : [region.points],
  };
}

const ringSignedArea = (ring: TissueRegion['points']) => {
  let area = 0;
  for (let index = 0; index < ring.length; index += 1) {
    const current = ring[index];
    const next = ring[(index + 1) % ring.length];
    if (!current || !next) continue;
    area += current.x * next.y - next.x * current.y;
  }
  return area / 2;
};

export function getAutoGeneratedGeometryRegions(region: TissueRegion): Region[] {
  const normalized = normalizeTissueRegion(region);
  const paths = normalized.paths ?? [normalized.points];
  if (!paths.length) {
    return [];
  }

  const firstNonZeroAreaPath = paths.find((path) => Math.abs(ringSignedArea(path)) > 1e-9);
  const outerAreaSign = firstNonZeroAreaPath && ringSignedArea(firstNonZeroAreaPath) < 0 ? -1 : 1;

  const outerRegions: Region[] = [];
  const holePaths: TissueRegion['points'][] = [];

  paths.forEach((path) => {
    if (path.length < 3) {
      return;
    }

    const area = ringSignedArea(path);
    const sign = area < 0 ? -1 : 1;

    if (sign === outerAreaSign) {
      outerRegions.push({
        id: normalized.id,
        label: 0,
        color: normalized.color,
        points: path,
        paths: [path],
      });
      return;
    }

    holePaths.push(path);
  });

  if (outerRegions.length === 0) {
    return [toGeometryRegion(normalized)];
  }

  holePaths.forEach((holePath) => {
    const anchor = holePath[0];
    if (!anchor) {
      return;
    }

    let bestRegionIndex = -1;
    let bestRegionArea = Number.POSITIVE_INFINITY;

    outerRegions.forEach((outerRegion, index) => {
      if (!pointInRing(anchor, outerRegion.points)) {
        return;
      }

      const area = Math.abs(ringSignedArea(outerRegion.points));
      if (area < bestRegionArea) {
        bestRegionArea = area;
        bestRegionIndex = index;
      }
    });

    if (bestRegionIndex >= 0) {
      const outerRegion = outerRegions[bestRegionIndex];
      if (!outerRegion) {
        return;
      }
      outerRegion.paths = [...(outerRegion.paths ?? [outerRegion.points]), holePath];
    }
  });

  return outerRegions;
}

const toGeometryRegion = (region: TissueRegion): Region => {
  const normalized = normalizeTissueRegion(region);
  return {
    id: normalized.id,
    label: 0,
    color: normalized.color,
    points: normalized.points,
    paths: normalized.paths,
  };
};

export function deriveSelectedSpotIdsFromRegions(
  regions: TissueRegion[],
  projectedSpots: ProjectedSpot[],
): string[] {
  if (regions.length === 0) {
    return [];
  }

  const geometryRegions = regions.map(toGeometryRegion);

  return projectedSpots
    .filter((spot) => geometryRegions.some((region, index) => {
      const sourceRegion = regions[index];
      if (!sourceRegion) {
        return false;
      }

      const rect = {
        x: spot.x - spot.diameterX / 2,
        y: spot.y - spot.diameterY / 2,
        width: spot.diameterX,
        height: spot.diameterY,
      };

      if (isAutoGeneratedTissueRegion(sourceRegion)) {
        return getAutoGeneratedGeometryRegions(sourceRegion).some((geometryRegion) =>
          regionIntersectsRect(geometryRegion, rect),
        );
      }

      return regionIntersectsRect(region, rect);
    }))
    .map((spot) => spot.id);
}

export function buildDefaultTissueRegionFromDetectedSpots(args: {
  projectedSpots: ProjectedSpot[];
  selectedSpotIds: string[];
}): TissueRegion | null {
  const selectedIdSet = new Set(args.selectedSpotIds);
  const selectedSpots = args.projectedSpots.filter((spot) => selectedIdSet.has(spot.id));
  if (selectedSpots.length === 0) {
    return null;
  }

  const spotPolygons: PolygonGeometry[] = selectedSpots.map((spot) => [[
    [spot.x - spot.diameterX / 2, spot.y - spot.diameterY / 2],
    [spot.x + spot.diameterX / 2, spot.y - spot.diameterY / 2],
    [spot.x + spot.diameterX / 2, spot.y + spot.diameterY / 2],
    [spot.x - spot.diameterX / 2, spot.y + spot.diameterY / 2],
  ]]);
  let union: MultiPolygonGeometry = spotPolygons[0] ? [spotPolygons[0]] : [];
  for (const polygon of spotPolygons.slice(1)) {
    union = polygonClipping.union(union as never, polygon as never) as MultiPolygonGeometry;
  }
  const paths = union
    .flat()
    .filter((ring): ring is [number, number][] => Array.isArray(ring) && ring.length >= 3)
    .map((ring) => ring.slice(0, -1).map(([x, y]) => ({ x, y })));

  if (paths.length === 0) {
    return null;
  }

  return {
    id: AUTO_TISSUE_REGION_ID,
    label: 'Detected tissue',
    color: colorForLabel(0),
    points: paths[0],
    paths,
  };
}

export function buildSelectedCountSummary(selectedIds: string[], totalSpots: number): TissueParitySummary {
  const selectedCount = selectedIds.length;
  const selectedPercent = totalSpots > 0 ? (selectedCount / totalSpots) * 100 : 0;

  return {
    selectedCount,
    selectedPercent,
    maskCoverage: selectedPercent,
  };
}
